### ISSUE TITLE
Add more GPS fields to location endpoint

### ISSUE THREAD

**Issue by mgerst** [shiftdsm/Galavanting-Gnome#45]
We want to record most if not all of the GPS information returned by the FONA.

These are all the available fields:
https://github.com/shiftdsm/Galavanting-Gnome/blob/db73412a80b70f18ec49b601009dc0d04f4e4948/packages/firmware/src/gps.h#L4-L13

**Comment by tegandbiscuits** [comment]
`speed_mph` is something the Arduino would need to calculate from `speed_kph`. I don't think it's worth adding it just to have it when we could easily figure it out.

**Comment by mgerst** [comment]
I think I've already removed it in my branch actually. I'm more concerned about the rest of it.
